services:
  app:
    image: "${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_TAG_NAME}:latest"
    platform: linux/amd64
    container_name: app
    ports:
      - "8080:8080"
    environment:
      MYSQL_USERNAME: "${{ secrets.MYSQL_USERNAME }}"
      MYSQL_PASSWORD: "${{ secrets.MYSQL_PASSWORD }}"
      MYSQL_URL: "${{ secrets.MYSQL_URL }}"
      JPA_HIBERNATE_DDL: "${{ secrets.JPA_HIBERNATE_DDL }}"
      JWT_SECRET: "${{ secrets.JWT_SECRET }}"
      YOUR_ACCESS_KEY: "${{ secrets.YOUR_ACCESS_KEY }}"
      YOUR_SECRET_KEY: "${{ secrets.YOUR_SECRET_KEY }}"
      YOUR_BUCKET_NAME: "${{ secrets.YOUR_BUCKET_NAME }}"
      OAUTH2_GOOGLE_CLIENT_ID: "${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}"
      OAUTH2_GOOGLE_CLIENT_SECRET: "${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}"
      OAUTH2_KAKAO_CLIENT_ID: "${{ secrets.OAUTH2_KAKAO_CLIENT_ID }}"
      OAUTH2_KAKAO_CLIENT_SECRET: "${{ secrets.OAUTH2_KAKAO_CLIENT_SECRET }}"
      EMAIL_USERNAME: "${{ secrets.EMAIL_USERNAME }}"
      EMAIL_APP_PASSWORD: "${{ secrets.EMAIL_APP_PASSWORD }}"
      GEMINI_URL: "${{ secrets.GEMINI_URL }}"
      GEMINI_KEY: "${{ secrets.GEMINI_KEY }}"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
